FROM golang:alpine3.19

RUN apk add --no-cache gcc musl-dev git && \
    addgroup -S mercari && adduser -S trainee -G mercari

WORKDIR /app
COPY images/ ./images/
COPY db/ ./db/
COPY go/ ./go/


COPY go.sum ./
COPY go.mod ./ 

RUN chown -R trainee:mercari /app/db
RUN go mod tidy
RUN go build -o main ./go/main.go

USER trainee

EXPOSE 9000
CMD ["./main"]